#spring security user config

#spring.security.user.name=user
#spring.security.user.password=123

spring.application.name=mobile-banking-api
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mobile_banking
spring.datasource.username=postgres
spring.datasource.password=197520
#Config Spring Data JPA
#DDL = Data Definition Language
#CREATE ALTER RENAME
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/mbapi
media.server-path=D:/Houy/testupload
media.base-uri=http://localhost:8080
#spring.servlet.multipart.max-file-size=5MB
#spring.servlet.multipart.max-request-size=10MB

spring.threads.virtual.enabled=true
